# Docker compose version
version: '3.7'
# App networking
# We use a bridge network to connect the parts
networks:
  qrls:
    driver: bridge
# App Services
services:
  # The Node server
  web:
    # Build our docker image
    build:
      context: .
      dockerfile: Dockerfile
    image: qrls-app
    restart: unless-stopped
    container_name: qrls-web
    ports:
      # Bind the port in the .env
      - ${PORT}:${PORT}
    expose:
      # Expose the port in the .env
      - ${PORT}
    volumes:
      - .:/usr/src/qrls
    networks:
      - qrls
    depends_on:
      - db
  # The MySQL database
  db:
    image: mysql:5.7
    container_name: qrls-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./docker-compose/mysql:/docker-entrypoint-initdb.d
    networks:
      - qrls